### ISSUE TITLE
REQUEST/BUG?: missleading "MINTEMP fixed" message

### ISSUE THREAD

**Issue by Sedrah87** [prusa3d/Prusa-Firmware#2341]
Hi, 
my current Problem is: I have a broken bed thermistor wire.
In FW-version 3.8.0/3.8.1 (maybe other) I got midprint the message "MINTEMP fixed please restart" and the print stops. What I can't see there is a very short (1 sec?) message bevor "Err: MINTEMP **bed**"
So I replaced the extruder thermistor with no success. After several supportchats we could identify the problem by flashing 3.7.1 there came the message MINTEMP bed.
Maybe there is a way to show different messages for different broken thermistors. Think this will help all with a MINTEMP error.
Thanks

**Comment by Kelly12612** [comment]
I've had this same problem with my new MK3S.  I added a comment on the assembly manual page, I do not think that this wire should be routed through the heatbed power wire clamp. Instead this wire should go outside of that clamp, and then be routed into the wire wrap from the side.
It's just way too hard to ensure that the wire stays in that tiny channel in the clamp while you're tightening the clamp, and the instructions/pictures suggest that you tighten that clamp completely until no gap is showing between the pieces.  This wire is far too fragile to withstand that.
Thanks,
Kelly

**Comment by Tanischacat2009** [comment]
The thermister and heater cartridge wires attached to the hotend should have protection around them on the bottom closest to the hotend.  I have had six thermistor replacements since purchasing my mk3s last February and to prolong the life of the thermistor, I have resorted to using rubber heat shrink wire wrap around the thermistor and heat cartridge wires to add protection to them from rubbing, pulling or getting caught on things etc.  As an added bonus, melted filament does NOT stick to the rubber heat shrink wrap, thus reducing mishaps and possible wire damage from melted filament accumulating on and around the heater block.  Though the wires themselves are relatively in expensive to replace, this is a somewhat substantial repair and more so if a hotend replacement is also required or easier to do at the same time.  Having the wires enclosed near the hotend would greatly reduce the amount of thermistor/heat cartridge wire replacements needed.

**Comment by william14235** [comment]
I have not have any problems with my thermistor on my mk3, maybe there is a new design that has an effect on the extruder? I remember that the mk3 s is supposedly supposed to have a completely redesigned extruder.

**Comment by nordurljosahvida** [comment]
The MINTEMP FIXED error should absolutely distinguish between hotend and bed by saying MINTEMP BED FIXED and possibly MINTEMP HOTEND FIXED.

Mintemp and Mintemp BED are already two separate error messages, we should distinguish them after it's been fixed as well, otherwise users will keep ordering the wrong part to replace and the only solution to this is using repetier-host and checking the backlogs after a fail during a print.

**Comment by leptun** [comment]
The issue is fixed in the latest release. (3.9.0-RC1)

**Comment by nordurljosahvida** [comment]
@leptun amazing thanks!

**Comment by leptun** [comment]
@Sedrah87 Please close the issue.

**Comment by Diedhert** [comment]
I have a new printer, two weeks old. I got this error, replaced thermistor, and still have the error "Mintemp fixed'....

**Comment by 3d-gussner** [comment]
@Diedhert which printer which firmware what is your ambient temperature. Can check under support for the temperatures? Or what temp does your lcd shows when it is not printing?

**Comment by Diedhert** [comment]
HI @3d-gussner I have a Prusa MK3s which is about 3 weeks old now. Firmware is 3.8.1.
Ambient temperature must be 25-30° (4 printers in my room). 
I am not all the time in my room, so the last time it was cooling down and on 70°.
